sudo: false

env:
  global:
    - secure: "mTwYczj2ObFoBTwUTy/rk1o6Vx3VQCC/wkw+3//MWKmk2ZzrPh06ip++U/U41NTLstNZ8TiZcmWXTPutMcVisGJZjp+FAYglg1PNf2Ql2LOFDHkwjzpbkovLb6UI0herePB+r22DkwQV9IELrF1vA8AxGWJtKv3Qnws2yEILh+HaOPyNkYFfjA7PwQ7v1y0jGPEy+idx156TeiXmGJoQLeNFcPD+axyvjNSuDDkwpuP/vIojFzT1mmTiHKwNH26daF1XRjyDnnMlYYdyfFxV8W05vY0pautBux1t4iUBDhvtawJj3SpKUOWK2oM3RfBJix+EcAsRrb3jjCcsOfVoJBC/Df6F+zNQylbvTNjmEvo9QiqQGw97rBqeWhjCsnG/Olq9ibZ0Yv9aO37eVLrEfGuPk9pI48i5CWwLXRYh3QdidOfQQHVW7d3azC3oDc8cDDs3Q+Y6xQhxnTmR79czF3jCPCE1N53BHWLH7kt2Dvt0FeaDH4rbj7pk6pgMDFxmHXD2OT6Ufw5uq9DwG5/wBbSHyFk1f+zZHF9mUphn4+ut3MQ8G95LrDvFI7dIs479gXIHswECaF5QEG4dv6KJCN7Z2kSppiC8ALciYut4KoJ5h8W680wdiuVolxiCyYN/N7EAjx0GJY4Ka+EIAFFgONw9tRM5VuVOJkSKHsjRJ9E="

    - secure: "ZL7ll1T2CJmo48Y5Jx5U8GruB6akHQGrqTQUC3Cikbp5Gle4xymtenQFyxbVedQ4sn1TPCKVa6qbdaU6lscFwrK6YpSh+lKnZouTsu+3sA73rRbASIbSKvLv6gFdhncP3/tR9gpfNbRwJP/3At2zwAXkpihGAAuHFrTsEkPHyy4DXSy2vWVKjmKvSBGx44bQgu8ogNlb4YrfMWQgbtgtwtSJVe0GoDekJBa8hVXqF+jZDZ1jODvinKA/Dwlm2vr/SlTFB9hg0f8ZHM9VxPME8fPHkncXzKTBhWtAAiCyhZA91x2tIG0w0HVxsCCp+E5KVKGg7FCeiqwcq7s0F8dyKDuRJpBtyDGeTGR4sODkaQvHi5EjraS2T2rM8v36U70OiBPHYOQppVzTThna4eQmE3pgRs9GiYKjxp+d6Zi/Aq07DCDu8k+++qLuOCcfG2ADA4MnjjBEaMKs8mlSGGabDib/0exq2/LU3FUGDZs05eSI2jpca5BaumzjLXdBvI8Nb+xcsPBjLnCKutQSz19NI8qJsalL57I5JMcLdaetpmBgNCEdIYfizpgqkMq6P8dek0BKslRPco3Iia/aIg6UnIWHzXbXiZDrRY5+e06Hx9Wz0nIwGEdCZ4nfaYwAzUNooSNC0jCItlN+V7E15komC5oMRjk4iKjftasK0wtZVuU="


language: scala

jdk:
- oraclejdk7
- oraclejdk8

scala:
- 2.10.5
- 2.11.5

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

script:
- ./buildall.sh

notifications:
  email:
    recipients:
    - lossyrob@gmail.com

before_deploy:
- export LSU_VERSION_SUFFIX="-${TRAVIS_COMMIT:0:7}"

deploy:
- provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: azavea/scala-landsat-util
    branch: master
    jdk: oraclejdk7
    scala: 2.10.5

- provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: azavea/scala-landsat-util
    tags: true
    jdk: oraclejdk7
    scala: 2.10.5

after_deploy:
- rm -f "${HOME}/.bintray/.credentials"
